# Generated by Django 5.1 on 2024-08-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('customerEmail', models.EmailField(max_length=200)),
                ('customerSubject', models.CharField(max_length=100)),
                ('customerMessage', models.CharField(max_length=100)),
            ],
        ),
    ]
