# Generated by Django 5.1 on 2024-08-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITBranch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=200)),
                ('headOfDepartmentName', models.CharField(max_length=200)),
                ('departmentPhoneNo', models.IntegerField()),
                ('departmentEmailId', models.EmailField(max_length=200)),
            ],
        ),
    ]
